services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data_tanstackboilerplate:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tanstackboilerplate

volumes:
  postgres_data_tanstackboilerplate:
